### ISSUE TITLE
look of "my profile" page

### ISSUE THREAD

**Issue by zosiakr** [bmackenty/reflective-formative-computer-science-#44]
1. short term goal and long term goal are unequal sizes
2. the "learning reflection" and "statistics" areas touch the outer border of the page. it would look better if there was a little bit of space between the outer borders of these windows and the border of the whole page. 
3. when we press "manage this goals" in the goals sections it would be nice if we wouldn't be brought to a different page but could manage the goal within the same page. 
4. in the place where we manage our short and long term goals the left side of the whole page is covered in a column of random letters, which i think is some kind of error
5. in the same page the width of the "long term goal" window is larger than the width of the "short term goal" window
6. on the bottom of the same page it says "silly stuff here". 
7. the "short term goal" text box and the "all my goals" box are all surrounded by one big border while the "long term goal" isn't included in that border and doesn't even have a border for itself

**Comment by bmackenty** [comment]
1. fixed (I think)
2. I need to see this on a laptop screen. On a desktop it looks pretty balanced and centered
3. I understand your point, and it kind of makes sense. However, I wanted only one place where people could add and manage their goals. I could just move it all over to the profile page, and remove the goal page. 
4. this has been fixed
5. Fixed
6. Fixed
7. Fixed. 

Hey Zosia. THANK YOU for your feedback. Next time, please make a separate issue report for each issue (I know it is a bit more work for you, but it's easier for me to address one issue at a time).
