### ISSUE TITLE
Duplicate "related" results

### ISSUE THREAD

**Issue by QingyuChai** [bmackenty/reflective-formative-computer-science-#45]
![screen shot 2018-01-09 at 10 39 38](https://user-images.githubusercontent.com/24941488/34714330-7609b8b0-f529-11e7-8aa4-cb193951055f.png)

The problem is on the page ["Identify different types of networks"](https://computerscienceexams.org/learn/learning_reflection/5). The "Related Activities based on tags" returns the same page as 2 results.

**Comment by QingyuChai** [comment]
both results redirect to the same page

**Comment by bmackenty** [comment]
I fixed the link. The related entries thing isn't really going to work until I have about 20 to 30 entries. I'm going to close this for now, and I'll take a look at it when I have more related tags (and entries) to look at. THANK YOU!
