### ISSUE TITLE
"Courses" Redundancy

### ISSUE THREAD

**Issue by czachor0** [bmackenty/reflective-formative-computer-science-#47]
Why does one need a separate section of "Courses" in the "Forums", while the "Courses" are already included in the "Site tools"?

**Comment by bmackenty** [comment]
It's a good question. The forums are a place to **discuss** courses and the course page is a place to **see which learning reflections are linked**. I'm really considering killing the course discussion forums, but just in case someone has a question about grading, policy, or something like that, I'll keep it in for now. THANK YOU for this report.
